//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanControllServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_TakeChangeHistory
    {
        public int ID { get; set; }
        public string ValveID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserTake { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsNotified { get; set; }
    }
}
