//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanControllServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Valve_Status
    {
        public string ValveID { get; set; }
        public Nullable<double> Status { get; set; }
        public Nullable<double> Alarm { get; set; }
        public Nullable<double> Mode { get; set; }
        public Nullable<double> P1 { get; set; }
        public Nullable<double> P2 { get; set; }
        public Nullable<double> P2set { get; set; }
        public Nullable<double> Solar { get; set; }
        public Nullable<double> Acquy { get; set; }
        public Nullable<double> Temp { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> A0 { get; set; }
        public Nullable<double> A1 { get; set; }
        public Nullable<double> A2 { get; set; }
        public Nullable<double> A3 { get; set; }
        public Nullable<double> A4 { get; set; }
        public Nullable<double> A5 { get; set; }
        public Nullable<double> A6 { get; set; }
        public Nullable<double> A7 { get; set; }
        public Nullable<double> A8 { get; set; }
        public Nullable<double> A9 { get; set; }
        public Nullable<double> A10 { get; set; }
        public Nullable<double> A11 { get; set; }
        public Nullable<double> A12 { get; set; }
        public Nullable<double> A13 { get; set; }
        public Nullable<double> A14 { get; set; }
        public Nullable<double> A15 { get; set; }
        public Nullable<double> A16 { get; set; }
        public Nullable<double> A17 { get; set; }
        public Nullable<double> A18 { get; set; }
        public Nullable<double> A19 { get; set; }
        public Nullable<double> A20 { get; set; }
        public Nullable<double> A21 { get; set; }
        public Nullable<double> A22 { get; set; }
        public Nullable<double> A23 { get; set; }
        public Nullable<double> M0 { get; set; }
        public Nullable<double> SS { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
