//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanControllServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Valve_Setting
    {
        public string ValveID { get; set; }
        public string ValveTag { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
